[Feature/register] 회원가입 validation 구현
SamCoMo/DBZ-Backend pull request #39
Opened 2024-03-10 14:32 UTC by JGoo99

## 📌 Issues #22 

## Description

회원가입 시 입력받는 이메일, 닉네임, 비밀번호, 전화번호의 유효성을 검증합니다.

```
- 공통 : @NotBlank (null, 공백 불가)
- 이메일 : example@example.com (@ 과 . 필수)
- 닉네임 : 특수문자 제외 2자리 이상 10자리 이하
- 전화번호 : 01로 시작하는 3자리-4(or3)자리-4자리 (하이픈 필수)
- 비밀번호 : 영문자+특수문자+숫자를 포함하여 8자 이상
```

<br/>

### 회원가입 성공 시 응답

```
올바른 입력 후 회원가입 성공 시 201 created 응답을 반환합니다.
```

### 회원가입 실패 시 응답

1. 공백이나 빈 문자열 혹은 정규식 패턴에서 벗어난 경우

```
{
    "password": "비밀번호는 8자리 이상 16자리 이하의 영문 대소문자와 숫자로 입력해주세요.",
    "phone": "전화번호 형식이 올바르지 않습니다.",
    "nickname": "닉네임은 특수문자를 제왼한 2~10자 사이의 문자로 입력해주세요.",
    "email": "이메일 형식이 올바르지 않습니다."
}
```

2. null 인 경우

```
{
    "password": "비밀번호는 필수 항목 입니다.",
    "phone": "전화번호는 필수 항목 입니다.",
    "nickname": "닉네임은 필수 항목 입니다.",
    "email": "이메일은 필수 항목 입니다."
}
```

<br/>

## ✨ Description

- [x] Test 완료
- [x] FE 통일 완료

<br/>

## To Reviewers

### 예외 처리 코드

```java
// @Valid 유효성 검사 실패 시 예외 처리
@ExceptionHandler(MethodArgumentNotValidException.class)
public ResponseEntity<Map<String, String>> handleValidException(
    MethodArgumentNotValidException e) {

  Map<String, String> errorList = new HashMap<>();

  String[] arguments = Objects.requireNonNull(e.getDetailMessageArguments())[1]
      .toString().split(", and ");

  for (String arg : arguments) {
    String[] errorString = arg.split(": ");
    errorList.put(errorString[0], errorString[1]);
  }

  return ResponseEntity.status(BAD_REQUEST).body(errorList);
}
```

### 추가 설명 

```java
e.getDetailMessageArguments()
```
이 값은 Object[]  로 오고, 0 번째 인덱스는 아무것도 없습니다.
첫번째 인덱스에 `password: 비밀번호는 필수 항목 입니다., and email: 비밀번호는 필수 항목 입니다., and ...` 이런식으로 옵니다.

이걸 split 으로 자르는 과정을 두번 거쳐서 map 에 담아 반환합니다!

더 좋은 방법이 있다면 조언 부탁드려요!!

2024-03-10 15:11 UTC, Cassiiopeia commented on src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
> +            message = "올바르지 않은 이메일 형식 입니다.")
https://wildeveloperetrain.tistory.com/157

Pattern을 통하여 정규식으로 validator를 구현하는것을 잘 보았습니다. 
하지만 이번 프로젝트와 같이 이메일검증할때가 회원가입시 단 한번이고  
이메일 변경 등에 대한 부분을 구현하지않았을때는 1회성으로 사용하므로

해당 방법이 간단할수있지만 

기능이 추가함에 따라 다른 항목에서도 이메일항목을 검증하는 기능이 필요하게 될수도있을때 
@ValidEmail 와 같이  다른곳에서 사용해서 쓸수있게 커스텀 밸리데이션으로 구현하면 더 좋을 것 같습니다.

커스텀 밸리데이션을 구현해서 어노테이션을 사용해서 구현하게될때 재사용성의 향샹, 캡슐화 등의 장점이 있을것 같습니다.

2024-03-11 02:11 UTC, JGoo99 commented on src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
> +            message = "올바르지 않은 이메일 형식 입니다.")
와...진짜 좋은 정보 감사합니다!
사실 spring.validation 으로 커스텀 구현체를 만들었었는데 특정 dto 에만 적용할 수 있는 방법밖에 구현 못하겠더라구요...
이 방법이면 가능하겠네요!!!! 감사합니다 ㅎㅎ

2024-03-11 06:23 UTC, JGoo99 commented on src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
> +            message = "올바르지 않은 이메일 형식 입니다.")
음...근데 직접 구현해보니까 커스텀 validator 는 "세부적으로 검증해야 할 로직이 많을 때" 에 더 초점을 맞춰야 할 것 같아요. 
어노테이션을 구현한 건 처음이라 많은 걸 배웠지만, 구현해놓고 보니 @Email 을 붙이는 거랑 다를게 없네요!ㅎㅎ

예를 들어 "특정 이메일 주소는 안 된다" 이런 세부 검증 로직이 있다면 @Email 만으로는 검증이 안 되니까 커스텀의 의미가 있는데, 저희 서비스엔 정규식만 일치하면 되니까요!

2024-03-11 10:54 UTC, JuJaeng2 approved these changes
노션 글이랑 잘 봤습니다~!
항상 기본 제공되는 코드를 커스텀하게 변경해서 사용하는게 인상깊어요.
저는 항상 주는대로 사용하려고 노력했는데 필요하다면 커스텀해서 사용하는 것도 항상 생각해보려고 노력해야겠어요~!

고생하셨습니다~!

2024-03-12 00:55 UTC, JGoo99 commented on src/main/java/com/samcomo/dbz/member/model/constants/MemberRole.java
> +  GUEST("GUEST");
```java
@Getter
@RequiredArgsConstructor
public enum MemberRole {

  MEMBER("ROLE_MEMBER"),
  ADMIN("ROLE_ADMIN"),
  GUEST("GUEST");

  // 생략

  public static MemberRole get(String role) {
    return Optional.ofNullable(roleMap.get(role)).orElse(GUEST);
  }
}
```

아래 `get` 메서드에서 null 방지용으로 가져온건데 생각해보니 오히려 오류를 더 발생시킬 것 같네요!!

GUEST 는 없애고 Optional 로만 감싸는 걸로 수정하겠습니다!! 감사합니다.

2024-03-12 16:39 UTC, Cassiiopeia requested changes

2024-03-12 16:39 UTC, Cassiiopeia commented on src/main/java/com/samcomo/dbz/member/utils/EmailValidator.java
> +package com.samcomo.dbz.member.utils;
혹시 EmailValidator 와 EmailCheck 파일을 global - utils 로 뺼수있을까요????

Report와 Pin 부분에서도 Validator 를 사용해야할텐데 각자 api의 Util에서 핸들링하면 코드의 응집력이 떨어질것 같습니다.

2024-03-12 16:39 UTC, Cassiiopeia commented on src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
> +  private static final String DEFAULT_MESSAGE = "은(는) 필수 항목입니다.";
REQUIRED_FIELD_MESSAGE 처럼 더 직관적인 static 이름은 어떠신가요??

2024-03-13 01:02 UTC, JGoo99 commented on src/main/java/com/samcomo/dbz/member/utils/EmailValidator.java
> +package com.samcomo.dbz.member.utils;
동의합니다! global-utils 로 이동했습니다.

```
utils
├── EmailValidator.java
└── annotation
    └── EmailCheck.java
```

2024-03-13 02:03 UTC, merged